---
title: "Income Data Pre-Processing + Exploration"
author: "Sabah Usmani (su2145)"
date: "12/6/2022"
output: github_document
---

```{r import, echo=FALSE}
library(dplyr)
library(tidyverse)
```

```{r income_data_preprocessing, paged.print=TRUE}
#Loading income data 
incomedata <- read_csv("data/census_data/median_income.csv", skip = 1)

#Loading zipcode data 
zipcode_data <- read.csv("data/Modified_Zip_Code_Tabulation_Areas__MODZCTA_.csv")


incomedata_clean <- incomedata %>%  
  janitor::clean_names()  %>%
  select(geography, geographic_area_name, estimate_median_income_dollars_families_families, estimate_median_income_dollars_nonfamily_households_nonfamily_households) %>%
  rename (median_income_nonfamily = estimate_median_income_dollars_nonfamily_households_nonfamily_households, median_income_family = estimate_median_income_dollars_families_families) %>% 
  separate(geographic_area_name, c('delete', 'modzcta')) %>% 
  select(modzcta, median_income_family, median_income_nonfamily)

vaccine_data <- read.csv("data/coverage-by-modzcta-adults_03.09.22.csv") %>%
  janitor::clean_names() %>%
  mutate(modzcta = as.character(modzcta))

vaccine_data$modzcta <- gsub('\\s+', '', vaccine_data$modzcta)

```

```{r merege-dataset}
joined_dataset_income = merge(vaccine_data,incomedata_clean, by = "modzcta", all.x = TRUE)
```


