---
title: "Income Data Pre-Processing + Exploration"
author: "Sabah Usmani (su2145)"
date: "`r Sys.Date()`"
output: github_document
---

```{r import, echo=FALSE}
library(dplyr)
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r income_data_preprocessing, paged.print=TRUE}
#Loading income data 
incomedata <- read_csv("data/census_data/median_income.csv", skip = 1)

#Loading zipcode data 
zipcode_data <- read.csv("data/Modified_Zip_Code_Tabulation_Areas__MODZCTA_.csv")

incomedata_clean <- incomedata %>%  
  janitor::clean_names()  %>%
  select(geography, geographic_area_name, estimate_median_income_dollars_families_families, estimate_median_income_dollars_nonfamily_households_nonfamily_households) %>%
  rename (median_income_nonfamily = estimate_median_income_dollars_nonfamily_households_nonfamily_households, median_income_family = estimate_median_income_dollars_families_families) %>% 
  separate(geographic_area_name, c('delete', 'modzcta')) %>% 
  select(modzcta, median_income_family, median_income_nonfamily)

vaccine_data <- read.csv("data/coverage-by-modzcta-adults_03.09.22.csv") %>%
  janitor::clean_names() %>%
  mutate(modzcta = as.character(modzcta))

vaccine_data$modzcta <- gsub('\\s+', '', vaccine_data$modzcta)

```

```{r merege-dataset}
joined_dataset_income = merge(vaccine_data,incomedata_clean, by = "modzcta", all.x = TRUE)
```

```{r}
#Cleaning variables in joined data and changing into the correct variable type 

income_zip_clean <- joined_dataset_income %>%
  mutate(modzcta = as.numeric(modzcta), median_fam = as.numeric(median_income_family), median_nonfam = as.numeric(median_income_nonfamily)) %>% 
  mutate(median_fam = if_else(is.na(median_fam), 250000, median_fam)) %>% 
  filter(!is.na(median_nonfam)) %>% 
  select(modzcta, pop_denominator, count_partially_cumulative, count_fully_cumulative, count_1plus_cumulative, count_additional_cumulative, median_fam, median_nonfam, borough) %>% 
  mutate(Count_partially_prop = round(count_partially_cumulative/pop_denominator,2), Count_Fully_prop = round(count_fully_cumulative/pop_denominator,2), Count_1Plus_prop = round(count_1plus_cumulative/pop_denominator,2), Count_Additional_prop = round(count_additional_cumulative/pop_denominator,2), income_average = ((median_fam + median_nonfam)/2))

str(income_zip_clean)

```

```{r}
#GGPLOT of Vaccination and family median income and non family median income by borough

income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = median_fam, y=Count_Fully_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Vaccinated & Median Family Income by Zipcope/Borough", 
    x = "Median Family Income", 
    y = "Proportion Vaccinated (Count_Fully_Prop)")

#GGPLOT of Vaccination and nonfamily median income and non family median income by borough
income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = median_nonfam, y=Count_Fully_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Vaccinated & Median Nonfamily Income by Zipcope/Borough", 
    x = "Median nonfamily Income", 
    y = "Proportion Vaccinated (Count_Fully_Prop)")

#GGPLOT of Vaccination combined median income and non family median income by borough

income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = income_average, y=Count_Fully_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Vaccinated & Median Income by Zipcope/Borough", 
    x = "Median Income (family + nonfamily)", 
    y = "Proportion Vaccinated (Count_Fully_Prop)")


```

```{r}
#GGPLOT OF BOOSTER STATUS AND MEDIAN INCOME 
income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = median_fam, y=Count_Additional_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Boosted & Median Family Income by Zipcope/Borough", 
    x = "Median Family Income", 
    y = "Proportion Boosted (Count_Additional_Prop)")


income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = median_nonfam, y=Count_Additional_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Boosted & Median Nonfamily Income by Zipcope/Borough", 
    x = "Median nonfamily Income", 
    y = "Proportion Boosted (Count_Additional_Prop)")

income_zip_clean %>%
    ggplot() +
    geom_point(aes(x = income_average, y=Count_Additional_prop, color=borough), alpha = 0.5)+
  labs(
   title = "Proportion Boosted & Median  Income by Zipcope/Borough", 
    x = "Median Income (family + nonfamily)", 
    y = "Proportion Boosted (Count_Additional_Prop)")


```


